# Generated by Django 5.2.3 on 2025-06-26 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientodetalle',
            options={'verbose_name': 'Detalle de Movimiento', 'verbose_name_plural': 'Detalles de Movimiento'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_movimiento',
            field=models.CharField(default='TRASLADO', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_entrada', to='inventario.bodega'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='bodega_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_salida', to='inventario.bodega'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientodetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='autores',
            field=models.ManyToManyField(blank=True, to='inventario.autor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='editorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.editorial'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('LIBRO', 'Libro'), ('REVISTA', 'Revista'), ('DVD', 'DVD'), ('CD', 'CD'), ('OTRO', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='autor',
            unique_together={('nombre', 'apellido')},
        ),
        migrations.AlterUniqueTogether(
            name='movimientodetalle',
            unique_together={('movimiento', 'producto')},
        ),
    ]
