version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_libreria
    restart: always
    environment:
      MYSQL_DATABASE: libreria_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - libreria_net

volumes:
  db_data:

networks:
  libreria_net: